// Generated by unRap v1.06 by Kegetys

class cfgNonAIVehicles {
	class ProxyGoggles;	// External class reference
	class ProxyBysta;	// External class reference
	
	class ProxyPVS15_Rabinex : ProxyGoggles {
		scope = public;
		model = "\sbe_sotg\PVS15_Rabinex.p3d";
	};
	
	class ProxyPVS15_00 : ProxyGoggles {
		scope = public;
		model = "\sbe_sotg\PVS15_00.p3d";
	};
	
	class ProxyPVS15_02 : ProxyGoggles {
		scope = public;
		model = "\sbe_sotg\PVS15_02.p3d";
	};
	
	class ProxyPVS15_FAST : ProxyGoggles {
		scope = public;
		model = "\sbe_sotg\PVS15_FAST.p3d";
	};
};
