// Generated by unRap v1.06 by Kegetys
class CfgPatches {
	class dayz_extras {
		units[] = {};
		weapons[] = {};
		requiredVersion = 1.0;
		requiredAddons[] = {"CAData", "CACharacters", "CAWeapons"};
		version = 1.0;
		author[] = {"Sabre", "ArdvarkDB", "Lennard", "MistaD"};
	};
};
