// Generated by unRap v1.06 by Kegetys

class CfgVehicles {
	class FR_TL;	// External class reference
	class Survivor4_DZ : FR_TL {
		scope = public;
		displayName = "Guardian";
		vehicleClass = "Men";
		nameSound = "officer";
		attendant = false;
		canHideBodies = 1;
		canCarryBackPack = 1;
		accuracy = 2;	// accuracy needed to recognize type of this target
		nightVision = true;
		camouflage = 0.6;	// how dificult to spot - bigger - better spotable
		sensitivity = 2;	// sensor sensitivity
		faction = PMC_BAF;
		identityTypes[] = {"Language_BAF","USMC_Glasses"};
		faceType = "Man";
		
		class HitHead {
			armor = 0.7;
			material = -1;
			name = "head_hit";
			passThrough = true;
		};
		
		class HitBody {
			armor = 1.5;
			material = -1;
			name = "body";
			passThrough = true;
		};
		
		class HitHands {
			armor = 0.5;
			material = -1;
			name = "hands";
			passThrough = true;
		};
		
		class HitLegs {
			armor = 0.5;
			material = -1;
			name = "legs";
			passThrough = true;
		};
		hiddenSelections[] = {"_middlearm", "_lowerroll", "_middleroll"};
		model = "\sbe_sotg\sotg_secco.p3d";
		weapons[] = {"Throw", "Put"};
		respawnWeapons[] = {"Throw","Put"};
		respawnMagazines[] = {};
		backpack = "";
		magazines[] = {};

		class Wounds {
			tex[] = {};
			mat[] = {"sbe_sotg\data\body1.rvmat", "sbe_sotg\data\body1_wound1.rvmat", "sbe_sotg\data\body1_wound2.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_white.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_white_wounds.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_white_wounds2.rvmat", "ca\characters\heads\male\defaulthead\data\hhl.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds.rvmat", "ca\characters\heads\male\defaulthead\data\hhl_wounds2.rvmat"};
		};
	};
	class Soldier_Crew_PMC;
	class Bandit2_DZ : Soldier_Crew_PMC {
        scope = public;
		identityTypes[] = {"Language_BAF","Language_EN_EP1","USMC_Glasses","PMC_Glasses_PMC"};
		faceType = "Man";
		hiddenSelections[] = {"_middlearm", "_lowerroll", "_middleroll"};
		displayName = "Assassin";
		side = 1;
		weapons[] = {"Throw","Put"};
		model = "\ca\characters_E\GER\GER_rifleman";
		portrait = "\Ca\characters_E\data\portraits\ger_soldier_CA";
		magazines[] = {};
		backpack = "";
		respawnWeapons[] = {"Throw","Put"};
		respawnMagazines[] = {};
		canHideBodies = 1;
	};
};
